# Generated by Django 6.0.2 on 2026-02-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_project_github_project_image_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сертификата')),
                ('issuer', models.CharField(max_length=200, verbose_name='Организация')),
                ('date', models.DateField(verbose_name='Дата получение')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сертификата')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сертификат')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-date'],
            },
        ),
    ]
